version: '3'

services:
  project-lib:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/golang/lib
    container_name: project-lib
    volumes:
      - .:/home/golang/lib
    tty: true
